# Скрипт регенерации icon-registry.ts на основе текущей структуры папок
$iconsPath = ".\src\assets\icons"
$outputFile = ".\src\app\pages\ui-demo\icon-ui\icon-registry.ts"

Write-Host "Сканирую иконки в $iconsPath..." -ForegroundColor Cyan

# Собираем все SVG файлы
$icons = Get-ChildItem -Path $iconsPath -Recurse -Filter "*.svg" | Where-Object {
    $_.Directory.Name -ne 'icons'  # Исключаем файлы напрямую в src/assets/icons
}

# Группируем по категориям (папкам)
$categories = @{}
foreach ($icon in $icons) {
    $category = $icon.Directory.Name
    $relativePath = $icon.FullName.Replace((Resolve-Path $iconsPath).Path + '\', '').Replace('\', '/')
    $type = $relativePath -replace '\.svg$', ''
    $name = $icon.BaseName

    if (-not $categories.ContainsKey($category)) {
        $categories[$category] = @()
    }

    $categories[$category] += @{
        name = $name
        type = $type
        category = $category
    }
}

# Маппинг категорий на русские названия
$categoryNames = @{
    'actions' = 'Действия'
    'arrows' = 'Стрелки'
    'charts' = 'Графики'
    'communication' = 'Коммуникация'
    'editor' = 'Редактор'
    'files' = 'Файлы'
    'general' = 'Общие'
    'media' = 'Медиа'
    'rewind' = 'Плеер'
    'settings' = 'Настройки'
    'social' = 'Соцсети'
    'system' = 'Система'
    'time' = 'Время'
    'user' = 'Пользователь'
}

# Генерируем TypeScript код
$tsCode = @"
// src/app/pages/ui-demo/icon-ui/icon-registry.ts
// AUTO-GENERATED by regenerate-icon-registry.ps1
// DO NOT EDIT MANUALLY

import { IconMetadata } from './icon-metadata.model';

export interface IconCategory {
  category: string;
  icons: IconMetadata[];
}

export const ICON_REGISTRY: IconCategory[] = [
"@

# Сортируем категории
$sortedCategories = $categories.Keys | Sort-Object

foreach ($cat in $sortedCategories) {
    $catName = if ($categoryNames.ContainsKey($cat)) { $categoryNames[$cat] } else { $cat }
    $iconList = $categories[$cat] | Sort-Object { $_.name }

    $tsCode += "`n  {`n"
    $tsCode += "    `"category`": `"$catName`",`n"
    $tsCode += "    `"icons`": [`n"

    foreach ($icon in $iconList) {
        $tsCode += "      {`n"
        $tsCode += "        `"name`": `"$($icon.name)`",`n"
        $tsCode += "        `"type`": `"$($icon.type)`",`n"
        $tsCode += "        `"category`": `"$catName`"`n"
        $tsCode += "      },`n"
    }

    # Убираем последнюю запятую
    $tsCode = $tsCode.TrimEnd(",`n") + "`n"
    $tsCode += "    ]`n"
    $tsCode += "  },`n"
}

# Убираем последнюю запятую и закрываем массив
$tsCode = $tsCode.TrimEnd(",`n") + "`n"
$tsCode += "];`n"

# Записываем файл
Set-Content -Path $outputFile -Value $tsCode -Encoding UTF8

Write-Host "`n✅ Файл $outputFile успешно создан!" -ForegroundColor Green
Write-Host "Найдено категорий: $($categories.Count)" -ForegroundColor Yellow
Write-Host "Всего иконок: $($icons.Count)" -ForegroundColor Yellow

# Показываем статистику
Write-Host "`nСтатистика по категориям:" -ForegroundColor Cyan
foreach ($cat in $sortedCategories) {
    $count = $categories[$cat].Count
    $catName = if ($categoryNames.ContainsKey($cat)) { $categoryNames[$cat] } else { $cat }
    Write-Host "  $catName ($cat): $count иконок" -ForegroundColor White
}
