// src/app/pages/ui-demo/icon-ui/icon-registry.ts
// AUTO-GENERATED by BACKEND SYNC
// DO NOT EDIT MANUALLY

import { IconMetadata } from './icon-metadata.model';

export interface IconCategory {
  category: string;
  icons: IconMetadata[];
}

export const ICON_REGISTRY: IconCategory[] = [
  {
    "category": "редактор",
    "icons": [
      {
        "name": "av_stop",
        "type": "редактор/av_stop",
        "category": "редактор"
      }
    ]
  },
  {
    "category": "Действия",
    "icons": [
      {
        "name": "av_add",
        "type": "actions/av_add",
        "category": "Действия"
      },
      {
        "name": "av_calculator",
        "type": "actions/av_calculator",
        "category": "Действия"
      },
      {
        "name": "av_check_mark",
        "type": "actions/av_check_mark",
        "category": "Действия"
      },
      {
        "name": "av_close",
        "type": "actions/av_close",
        "category": "Действия"
      },
      {
        "name": "av_copy",
        "type": "actions/av_copy",
        "category": "Действия"
      },
      {
        "name": "av_eraser",
        "type": "actions/av_eraser",
        "category": "Действия"
      },
      {
        "name": "av_exit",
        "type": "actions/av_exit",
        "category": "Действия"
      },
      {
        "name": "av_eye",
        "type": "actions/av_eye",
        "category": "Действия"
      },
      {
        "name": "av_galka-ok",
        "type": "actions/av_galka-ok",
        "category": "Действия"
      },
      {
        "name": "av_hammer",
        "type": "actions/av_hammer",
        "category": "Действия"
      },
      {
        "name": "av_load-icon",
        "type": "actions/av_load-icon",
        "category": "Действия"
      },
      {
        "name": "av_minus",
        "type": "actions/av_minus",
        "category": "Действия"
      },
      {
        "name": "av_plus",
        "type": "actions/av_plus",
        "category": "Действия"
      },
      {
        "name": "av_save",
        "type": "actions/av_save",
        "category": "Действия"
      },
      {
        "name": "av_search",
        "type": "actions/av_search",
        "category": "Действия"
      },
      {
        "name": "av_trash",
        "type": "actions/av_trash",
        "category": "Действия"
      },
      {
        "name": "av_upload",
        "type": "actions/av_upload",
        "category": "Действия"
      }
    ]
  },
  {
    "category": "Стрелки",
    "icons": [
      {
        "name": "av_arrow-down",
        "type": "arrows/av_arrow-down",
        "category": "Стрелки"
      },
      {
        "name": "av_arrow-left",
        "type": "arrows/av_arrow-left",
        "category": "Стрелки"
      },
      {
        "name": "av_arrow-right",
        "type": "arrows/av_arrow-right",
        "category": "Стрелки"
      },
      {
        "name": "av_arrow-up",
        "type": "arrows/av_arrow-up",
        "category": "Стрелки"
      },
      {
        "name": "av_arrows_out",
        "type": "arrows/av_arrows_out",
        "category": "Стрелки"
      },
      {
        "name": "av_arrow_down",
        "type": "arrows/av_arrow_down",
        "category": "Стрелки"
      },
      {
        "name": "av_arrow_down_right",
        "type": "arrows/av_arrow_down_right",
        "category": "Стрелки"
      },
      {
        "name": "av_arrow_left",
        "type": "arrows/av_arrow_left",
        "category": "Стрелки"
      },
      {
        "name": "av_arrow_right",
        "type": "arrows/av_arrow_right",
        "category": "Стрелки"
      },
      {
        "name": "av_arrow_up",
        "type": "arrows/av_arrow_up",
        "category": "Стрелки"
      },
      {
        "name": "av_chevron-down",
        "type": "arrows/av_chevron-down",
        "category": "Стрелки"
      },
      {
        "name": "av_chevron-left",
        "type": "arrows/av_chevron-left",
        "category": "Стрелки"
      },
      {
        "name": "av_chevron-right",
        "type": "arrows/av_chevron-right",
        "category": "Стрелки"
      },
      {
        "name": "av_chevron-up",
        "type": "arrows/av_chevron-up",
        "category": "Стрелки"
      },
      {
        "name": "av_expand",
        "type": "arrows/av_expand",
        "category": "Стрелки"
      },
      {
        "name": "av_fast_forward",
        "type": "arrows/av_fast_forward",
        "category": "Стрелки"
      },
      {
        "name": "av_triangle-down",
        "type": "arrows/av_triangle-down",
        "category": "Стрелки"
      },
      {
        "name": "av_triangle-left",
        "type": "arrows/av_triangle-left",
        "category": "Стрелки"
      },
      {
        "name": "av_triangle-right",
        "type": "arrows/av_triangle-right",
        "category": "Стрелки"
      },
      {
        "name": "av_triangle-up",
        "type": "arrows/av_triangle-up",
        "category": "Стрелки"
      },
      {
        "name": "av_undo",
        "type": "arrows/av_undo",
        "category": "Стрелки"
      }
    ]
  },
  {
    "category": "Графики",
    "icons": [
      {
        "name": "av_bar_chart",
        "type": "charts/av_bar_chart",
        "category": "Графики"
      },
      {
        "name": "av_line_chart",
        "type": "charts/av_line_chart",
        "category": "Графики"
      },
      {
        "name": "av_pie_chart",
        "type": "charts/av_pie_chart",
        "category": "Графики"
      }
    ]
  },
  {
    "category": "Коммуникация",
    "icons": [
      {
        "name": "av_chat",
        "type": "communication/av_chat",
        "category": "Коммуникация"
      },
      {
        "name": "av_mail",
        "type": "communication/av_mail",
        "category": "Коммуникация"
      },
      {
        "name": "av_phone",
        "type": "communication/av_phone",
        "category": "Коммуникация"
      },
      {
        "name": "av_rss",
        "type": "communication/av_rss",
        "category": "Коммуникация"
      }
    ]
  },
  {
    "category": "Редактор",
    "icons": [
      {
        "name": "av_align-center",
        "type": "editor/av_align-center",
        "category": "Редактор"
      },
      {
        "name": "av_align-justify",
        "type": "editor/av_align-justify",
        "category": "Редактор"
      },
      {
        "name": "av_align-left",
        "type": "editor/av_align-left",
        "category": "Редактор"
      },
      {
        "name": "av_align-right",
        "type": "editor/av_align-right",
        "category": "Редактор"
      },
      {
        "name": "av_alignment-big",
        "type": "editor/av_alignment-big",
        "category": "Редактор"
      },
      {
        "name": "av_align_center",
        "type": "editor/av_align_center",
        "category": "Редактор"
      },
      {
        "name": "av_align_right",
        "type": "editor/av_align_right",
        "category": "Редактор"
      },
      {
        "name": "av_bold",
        "type": "editor/av_bold",
        "category": "Редактор"
      },
      {
        "name": "av_bulleted-list",
        "type": "editor/av_bulleted-list",
        "category": "Редактор"
      },
      {
        "name": "av_edit",
        "type": "editor/av_edit",
        "category": "Редактор"
      },
      {
        "name": "av_font",
        "type": "editor/av_font",
        "category": "Редактор"
      },
      {
        "name": "av_format-list-numbered",
        "type": "editor/av_format-list-numbered",
        "category": "Редактор"
      },
      {
        "name": "av_input-quote",
        "type": "editor/av_input-quote",
        "category": "Редактор"
      },
      {
        "name": "av_italic",
        "type": "editor/av_italic",
        "category": "Редактор"
      },
      {
        "name": "av_list-numbered",
        "type": "editor/av_list-numbered",
        "category": "Редактор"
      },
      {
        "name": "av_list-svgrepo",
        "type": "editor/av_list-svgrepo",
        "category": "Редактор"
      },
      {
        "name": "av_list",
        "type": "editor/av_list",
        "category": "Редактор"
      },
      {
        "name": "av_open-font",
        "type": "editor/av_open-font",
        "category": "Редактор"
      },
      {
        "name": "av_paint",
        "type": "editor/av_paint",
        "category": "Редактор"
      },
      {
        "name": "av_quote",
        "type": "editor/av_quote",
        "category": "Редактор"
      },
      {
        "name": "av_stop",
        "type": "editor/av_stop",
        "category": "Редактор"
      },
      {
        "name": "av_style-quote",
        "type": "editor/av_style-quote",
        "category": "Редактор"
      },
      {
        "name": "av_writing",
        "type": "editor/av_writing",
        "category": "Редактор"
      }
    ]
  },
  {
    "category": "Файлы",
    "icons": [
      {
        "name": "av_excel",
        "type": "files/av_excel",
        "category": "Файлы"
      },
      {
        "name": "av_folder",
        "type": "files/av_folder",
        "category": "Файлы"
      },
      {
        "name": "av_paperclip",
        "type": "files/av_paperclip",
        "category": "Файлы"
      },
      {
        "name": "av_zip",
        "type": "files/av_zip",
        "category": "Файлы"
      }
    ]
  },
  {
    "category": "Общие",
    "icons": [
      {
        "name": "av_alert-circle",
        "type": "general/av_alert-circle",
        "category": "Общие"
      },
      {
        "name": "av_alert-triangle",
        "type": "general/av_alert-triangle",
        "category": "Общие"
      },
      {
        "name": "av_align-center",
        "type": "general/av_align-center",
        "category": "Общие"
      },
      {
        "name": "av_align-justify",
        "type": "general/av_align-justify",
        "category": "Общие"
      },
      {
        "name": "av_align-left",
        "type": "general/av_align-left",
        "category": "Общие"
      },
      {
        "name": "av_align-right",
        "type": "general/av_align-right",
        "category": "Общие"
      },
      {
        "name": "av_api",
        "type": "general/av_api",
        "category": "Общие"
      },
      {
        "name": "av_arrow-down-circle",
        "type": "general/av_arrow-down-circle",
        "category": "Общие"
      },
      {
        "name": "av_arrow-down-left",
        "type": "general/av_arrow-down-left",
        "category": "Общие"
      },
      {
        "name": "av_arrow-down-right",
        "type": "general/av_arrow-down-right",
        "category": "Общие"
      },
      {
        "name": "av_arrow-down",
        "type": "general/av_arrow-down",
        "category": "Общие"
      },
      {
        "name": "av_arrow-left",
        "type": "general/av_arrow-left",
        "category": "Общие"
      },
      {
        "name": "av_arrow-right-circle",
        "type": "general/av_arrow-right-circle",
        "category": "Общие"
      },
      {
        "name": "av_arrow-right",
        "type": "general/av_arrow-right",
        "category": "Общие"
      },
      {
        "name": "av_arrow-up-circle",
        "type": "general/av_arrow-up-circle",
        "category": "Общие"
      },
      {
        "name": "av_arrow-up-left",
        "type": "general/av_arrow-up-left",
        "category": "Общие"
      },
      {
        "name": "av_arrow-up-right",
        "type": "general/av_arrow-up-right",
        "category": "Общие"
      },
      {
        "name": "av_arrow-up",
        "type": "general/av_arrow-up",
        "category": "Общие"
      },
      {
        "name": "av_at-sign",
        "type": "general/av_at-sign",
        "category": "Общие"
      },
      {
        "name": "av_black-mac-folder-13646",
        "type": "general/av_black-mac-folder-13646",
        "category": "Общие"
      },
      {
        "name": "av_blue-linkedin-logo-15916",
        "type": "general/av_blue-linkedin-logo-15916",
        "category": "Общие"
      },
      {
        "name": "av_blue-twitter-verified-sign-18759",
        "type": "general/av_blue-twitter-verified-sign-18759",
        "category": "Общие"
      },
      {
        "name": "av_bold",
        "type": "general/av_bold",
        "category": "Общие"
      },
      {
        "name": "av_book",
        "type": "general/av_book",
        "category": "Общие"
      },
      {
        "name": "av_bookmark",
        "type": "general/av_bookmark",
        "category": "Общие"
      },
      {
        "name": "av_businessman",
        "type": "general/av_businessman",
        "category": "Общие"
      },
      {
        "name": "av_chatgpt-green-circular-logo-22057",
        "type": "general/av_chatgpt-green-circular-logo-22057",
        "category": "Общие"
      },
      {
        "name": "av_check-7050",
        "type": "general/av_check-7050",
        "category": "Общие"
      },
      {
        "name": "av_check-circle",
        "type": "general/av_check-circle",
        "category": "Общие"
      },
      {
        "name": "av_check-mark-10126",
        "type": "general/av_check-mark-10126",
        "category": "Общие"
      },
      {
        "name": "av_check-square",
        "type": "general/av_check-square",
        "category": "Общие"
      },
      {
        "name": "av_chevron-down",
        "type": "general/av_chevron-down",
        "category": "Общие"
      },
      {
        "name": "av_chevron-left",
        "type": "general/av_chevron-left",
        "category": "Общие"
      },
      {
        "name": "av_chevron-right",
        "type": "general/av_chevron-right",
        "category": "Общие"
      },
      {
        "name": "av_chevron-up",
        "type": "general/av_chevron-up",
        "category": "Общие"
      },
      {
        "name": "av_chevrons-down",
        "type": "general/av_chevrons-down",
        "category": "Общие"
      },
      {
        "name": "av_chevrons-left",
        "type": "general/av_chevrons-left",
        "category": "Общие"
      },
      {
        "name": "av_chevrons-right",
        "type": "general/av_chevrons-right",
        "category": "Общие"
      },
      {
        "name": "av_chevrons-up",
        "type": "general/av_chevrons-up",
        "category": "Общие"
      },
      {
        "name": "av_code",
        "type": "general/av_code",
        "category": "Общие"
      },
      {
        "name": "av_component",
        "type": "general/av_component",
        "category": "Общие"
      },
      {
        "name": "av_copy",
        "type": "general/av_copy",
        "category": "Общие"
      },
      {
        "name": "av_corner-down-left",
        "type": "general/av_corner-down-left",
        "category": "Общие"
      },
      {
        "name": "av_corner-down-right",
        "type": "general/av_corner-down-right",
        "category": "Общие"
      },
      {
        "name": "av_corner-left-down",
        "type": "general/av_corner-left-down",
        "category": "Общие"
      },
      {
        "name": "av_corner-left-up",
        "type": "general/av_corner-left-up",
        "category": "Общие"
      },
      {
        "name": "av_corner-right-down",
        "type": "general/av_corner-right-down",
        "category": "Общие"
      },
      {
        "name": "av_corner-right-up",
        "type": "general/av_corner-right-up",
        "category": "Общие"
      },
      {
        "name": "av_corner-up-left",
        "type": "general/av_corner-up-left",
        "category": "Общие"
      },
      {
        "name": "av_corner-up-right",
        "type": "general/av_corner-up-right",
        "category": "Общие"
      },
      {
        "name": "av_crop",
        "type": "general/av_crop",
        "category": "Общие"
      },
      {
        "name": "av_database",
        "type": "general/av_database",
        "category": "Общие"
      },
      {
        "name": "av_delete",
        "type": "general/av_delete",
        "category": "Общие"
      },
      {
        "name": "av_dice",
        "type": "general/av_dice",
        "category": "Общие"
      },
      {
        "name": "av_dollar-sign",
        "type": "general/av_dollar-sign",
        "category": "Общие"
      },
      {
        "name": "av_download-cloud",
        "type": "general/av_download-cloud",
        "category": "Общие"
      },
      {
        "name": "av_download",
        "type": "general/av_download",
        "category": "Общие"
      },
      {
        "name": "av_droplet",
        "type": "general/av_droplet",
        "category": "Общие"
      },
      {
        "name": "av_earth",
        "type": "general/av_earth",
        "category": "Общие"
      },
      {
        "name": "av_edit-2",
        "type": "general/av_edit-2",
        "category": "Общие"
      },
      {
        "name": "av_edit-3",
        "type": "general/av_edit-3",
        "category": "Общие"
      },
      {
        "name": "av_edit",
        "type": "general/av_edit",
        "category": "Общие"
      },
      {
        "name": "av_error-failure-10382",
        "type": "general/av_error-failure-10382",
        "category": "Общие"
      },
      {
        "name": "av_external-link",
        "type": "general/av_external-link",
        "category": "Общие"
      },
      {
        "name": "av_eye-off",
        "type": "general/av_eye-off",
        "category": "Общие"
      },
      {
        "name": "av_eye",
        "type": "general/av_eye",
        "category": "Общие"
      },
      {
        "name": "av_facebook-logo",
        "type": "general/av_facebook-logo",
        "category": "Общие"
      },
      {
        "name": "av_file-minus",
        "type": "general/av_file-minus",
        "category": "Общие"
      },
      {
        "name": "av_file-plus",
        "type": "general/av_file-plus",
        "category": "Общие"
      },
      {
        "name": "av_file-text",
        "type": "general/av_file-text",
        "category": "Общие"
      },
      {
        "name": "av_file",
        "type": "general/av_file",
        "category": "Общие"
      },
      {
        "name": "av_flag",
        "type": "general/av_flag",
        "category": "Общие"
      },
      {
        "name": "av_folder-plus",
        "type": "general/av_folder-plus",
        "category": "Общие"
      },
      {
        "name": "av_folder",
        "type": "general/av_folder",
        "category": "Общие"
      },
      {
        "name": "av_gear-1213",
        "type": "general/av_gear-1213",
        "category": "Общие"
      },
      {
        "name": "av_github",
        "type": "general/av_github",
        "category": "Общие"
      },
      {
        "name": "av_globe",
        "type": "general/av_globe",
        "category": "Общие"
      },
      {
        "name": "av_green-arrow-up-11385",
        "type": "general/av_green-arrow-up-11385",
        "category": "Общие"
      },
      {
        "name": "av_green-check-mark-correct-tick",
        "type": "general/av_green-check-mark-correct-tick",
        "category": "Общие"
      },
      {
        "name": "av_grid",
        "type": "general/av_grid",
        "category": "Общие"
      },
      {
        "name": "av_hash",
        "type": "general/av_hash",
        "category": "Общие"
      },
      {
        "name": "av_heart-329",
        "type": "general/av_heart-329",
        "category": "Общие"
      },
      {
        "name": "av_heart",
        "type": "general/av_heart",
        "category": "Общие"
      },
      {
        "name": "av_help-circle",
        "type": "general/av_help-circle",
        "category": "Общие"
      },
      {
        "name": "av_home-175",
        "type": "general/av_home-175",
        "category": "Общие"
      },
      {
        "name": "av_home-2490",
        "type": "general/av_home-2490",
        "category": "Общие"
      },
      {
        "name": "av_home",
        "type": "general/av_home",
        "category": "Общие"
      },
      {
        "name": "av_house",
        "type": "general/av_house",
        "category": "Общие"
      },
      {
        "name": "av_image",
        "type": "general/av_image",
        "category": "Общие"
      },
      {
        "name": "av_india-flag-circular-17791",
        "type": "general/av_india-flag-circular-17791",
        "category": "Общие"
      },
      {
        "name": "av_iphone-phone-green-button-21468",
        "type": "general/av_iphone-phone-green-button-21468",
        "category": "Общие"
      },
      {
        "name": "av_italic",
        "type": "general/av_italic",
        "category": "Общие"
      },
      {
        "name": "av_key",
        "type": "general/av_key",
        "category": "Общие"
      },
      {
        "name": "av_like",
        "type": "general/av_like",
        "category": "Общие"
      },
      {
        "name": "av_link-2",
        "type": "general/av_link-2",
        "category": "Общие"
      },
      {
        "name": "av_link",
        "type": "general/av_link",
        "category": "Общие"
      },
      {
        "name": "av_linkedin-130",
        "type": "general/av_linkedin-130",
        "category": "Общие"
      },
      {
        "name": "av_list-numbered",
        "type": "general/av_list-numbered",
        "category": "Общие"
      },
      {
        "name": "av_list",
        "type": "general/av_list",
        "category": "Общие"
      },
      {
        "name": "av_loader",
        "type": "general/av_loader",
        "category": "Общие"
      },
      {
        "name": "av_log-in",
        "type": "general/av_log-in",
        "category": "Общие"
      },
      {
        "name": "av_log-out",
        "type": "general/av_log-out",
        "category": "Общие"
      },
      {
        "name": "av_mail",
        "type": "general/av_mail",
        "category": "Общие"
      },
      {
        "name": "av_male-symbol-2239",
        "type": "general/av_male-symbol-2239",
        "category": "Общие"
      },
      {
        "name": "av_map-pin",
        "type": "general/av_map-pin",
        "category": "Общие"
      },
      {
        "name": "av_maximize-2",
        "type": "general/av_maximize-2",
        "category": "Общие"
      },
      {
        "name": "av_maximize",
        "type": "general/av_maximize",
        "category": "Общие"
      },
      {
        "name": "av_menu",
        "type": "general/av_menu",
        "category": "Общие"
      },
      {
        "name": "av_message-circle",
        "type": "general/av_message-circle",
        "category": "Общие"
      },
      {
        "name": "av_message-square",
        "type": "general/av_message-square",
        "category": "Общие"
      },
      {
        "name": "av_minimize-2",
        "type": "general/av_minimize-2",
        "category": "Общие"
      },
      {
        "name": "av_minimize",
        "type": "general/av_minimize",
        "category": "Общие"
      },
      {
        "name": "av_minus-circle",
        "type": "general/av_minus-circle",
        "category": "Общие"
      },
      {
        "name": "av_minus-square",
        "type": "general/av_minus-square",
        "category": "Общие"
      },
      {
        "name": "av_minus",
        "type": "general/av_minus",
        "category": "Общие"
      },
      {
        "name": "av_more-horizontal",
        "type": "general/av_more-horizontal",
        "category": "Общие"
      },
      {
        "name": "av_more-vertical",
        "type": "general/av_more-vertical",
        "category": "Общие"
      },
      {
        "name": "av_note",
        "type": "general/av_note",
        "category": "Общие"
      },
      {
        "name": "av_number-one-13217",
        "type": "general/av_number-one-13217",
        "category": "Общие"
      },
      {
        "name": "av_page",
        "type": "general/av_page",
        "category": "Общие"
      },
      {
        "name": "av_paperclip",
        "type": "general/av_paperclip",
        "category": "Общие"
      },
      {
        "name": "av_pdf-2616",
        "type": "general/av_pdf-2616",
        "category": "Общие"
      },
      {
        "name": "av_pdf-download-3388",
        "type": "general/av_pdf-download-3388",
        "category": "Общие"
      },
      {
        "name": "av_percent",
        "type": "general/av_percent",
        "category": "Общие"
      },
      {
        "name": "av_pinterest-113",
        "type": "general/av_pinterest-113",
        "category": "Общие"
      },
      {
        "name": "av_play-button-4213",
        "type": "general/av_play-button-4213",
        "category": "Общие"
      },
      {
        "name": "av_plus-circle",
        "type": "general/av_plus-circle",
        "category": "Общие"
      },
      {
        "name": "av_plus-square",
        "type": "general/av_plus-square",
        "category": "Общие"
      },
      {
        "name": "av_plus",
        "type": "general/av_plus",
        "category": "Общие"
      },
      {
        "name": "av_power",
        "type": "general/av_power",
        "category": "Общие"
      },
      {
        "name": "av_red-arrow-down-11380",
        "type": "general/av_red-arrow-down-11380",
        "category": "Общие"
      },
      {
        "name": "av_refresh-ccw",
        "type": "general/av_refresh-ccw",
        "category": "Общие"
      },
      {
        "name": "av_refresh-cw",
        "type": "general/av_refresh-cw",
        "category": "Общие"
      },
      {
        "name": "av_repeat",
        "type": "general/av_repeat",
        "category": "Общие"
      },
      {
        "name": "av_road",
        "type": "general/av_road",
        "category": "Общие"
      },
      {
        "name": "av_rotate-ccw",
        "type": "general/av_rotate-ccw",
        "category": "Общие"
      },
      {
        "name": "av_rotate-cw",
        "type": "general/av_rotate-cw",
        "category": "Общие"
      },
      {
        "name": "av_russia-flag-circular-17765",
        "type": "general/av_russia-flag-circular-17765",
        "category": "Общие"
      },
      {
        "name": "av_sad-face-2692",
        "type": "general/av_sad-face-2692",
        "category": "Общие"
      },
      {
        "name": "av_save",
        "type": "general/av_save",
        "category": "Общие"
      },
      {
        "name": "av_search-tolstii",
        "type": "general/av_search-tolstii",
        "category": "Общие"
      },
      {
        "name": "av_search",
        "type": "general/av_search",
        "category": "Общие"
      },
      {
        "name": "av_settings-5666",
        "type": "general/av_settings-5666",
        "category": "Общие"
      },
      {
        "name": "av_settings",
        "type": "general/av_settings",
        "category": "Общие"
      },
      {
        "name": "av_share",
        "type": "general/av_share",
        "category": "Общие"
      },
      {
        "name": "av_shopping-cart-3041",
        "type": "general/av_shopping-cart-3041",
        "category": "Общие"
      },
      {
        "name": "av_shopping-cart-3045",
        "type": "general/av_shopping-cart-3045",
        "category": "Общие"
      },
      {
        "name": "av_shopping-cart",
        "type": "general/av_shopping-cart",
        "category": "Общие"
      },
      {
        "name": "av_skype-132",
        "type": "general/av_skype-132",
        "category": "Общие"
      },
      {
        "name": "av_smile",
        "type": "general/av_smile",
        "category": "Общие"
      },
      {
        "name": "av_star",
        "type": "general/av_star",
        "category": "Общие"
      },
      {
        "name": "av_stop-circle",
        "type": "general/av_stop-circle",
        "category": "Общие"
      },
      {
        "name": "av_table",
        "type": "general/av_table",
        "category": "Общие"
      },
      {
        "name": "av_tag",
        "type": "general/av_tag",
        "category": "Общие"
      },
      {
        "name": "av_telegram-logo",
        "type": "general/av_telegram-logo",
        "category": "Общие"
      },
      {
        "name": "av_thermometer",
        "type": "general/av_thermometer",
        "category": "Общие"
      },
      {
        "name": "av_thumbs-down-14922",
        "type": "general/av_thumbs-down-14922",
        "category": "Общие"
      },
      {
        "name": "av_thumbs-down-14924",
        "type": "general/av_thumbs-down-14924",
        "category": "Общие"
      },
      {
        "name": "av_thumbs-down",
        "type": "general/av_thumbs-down",
        "category": "Общие"
      },
      {
        "name": "av_thumbs-up",
        "type": "general/av_thumbs-up",
        "category": "Общие"
      },
      {
        "name": "av_ticket",
        "type": "general/av_ticket",
        "category": "Общие"
      },
      {
        "name": "av_tiktok-logo-10295",
        "type": "general/av_tiktok-logo-10295",
        "category": "Общие"
      },
      {
        "name": "av_toggle-left",
        "type": "general/av_toggle-left",
        "category": "Общие"
      },
      {
        "name": "av_toggle-right",
        "type": "general/av_toggle-right",
        "category": "Общие"
      },
      {
        "name": "av_tool",
        "type": "general/av_tool",
        "category": "Общие"
      },
      {
        "name": "av_trash-2",
        "type": "general/av_trash-2",
        "category": "Общие"
      },
      {
        "name": "av_trash",
        "type": "general/av_trash",
        "category": "Общие"
      },
      {
        "name": "av_triangle",
        "type": "general/av_triangle",
        "category": "Общие"
      },
      {
        "name": "av_trophy",
        "type": "general/av_trophy",
        "category": "Общие"
      },
      {
        "name": "av_truck",
        "type": "general/av_truck",
        "category": "Общие"
      },
      {
        "name": "av_tv",
        "type": "general/av_tv",
        "category": "Общие"
      },
      {
        "name": "av_twitter",
        "type": "general/av_twitter",
        "category": "Общие"
      },
      {
        "name": "av_type",
        "type": "general/av_type",
        "category": "Общие"
      },
      {
        "name": "av_umbrella",
        "type": "general/av_umbrella",
        "category": "Общие"
      },
      {
        "name": "av_underline",
        "type": "general/av_underline",
        "category": "Общие"
      },
      {
        "name": "av_united-arab-emirates-flag-circular-17754",
        "type": "general/av_united-arab-emirates-flag-circular-17754",
        "category": "Общие"
      },
      {
        "name": "av_user-check",
        "type": "general/av_user-check",
        "category": "Общие"
      },
      {
        "name": "av_user-minus",
        "type": "general/av_user-minus",
        "category": "Общие"
      },
      {
        "name": "av_user-plus",
        "type": "general/av_user-plus",
        "category": "Общие"
      },
      {
        "name": "av_user-x",
        "type": "general/av_user-x",
        "category": "Общие"
      },
      {
        "name": "av_user",
        "type": "general/av_user",
        "category": "Общие"
      },
      {
        "name": "av_users-267",
        "type": "general/av_users-267",
        "category": "Общие"
      },
      {
        "name": "av_users",
        "type": "general/av_users",
        "category": "Общие"
      },
      {
        "name": "av_visa-credit-card-payment",
        "type": "general/av_visa-credit-card-payment",
        "category": "Общие"
      },
      {
        "name": "av_vk-120",
        "type": "general/av_vk-120",
        "category": "Общие"
      },
      {
        "name": "av_warning-sign-9763",
        "type": "general/av_warning-sign-9763",
        "category": "Общие"
      },
      {
        "name": "av_website-4946",
        "type": "general/av_website-4946",
        "category": "Общие"
      },
      {
        "name": "av_whatsapp-139",
        "type": "general/av_whatsapp-139",
        "category": "Общие"
      },
      {
        "name": "av_wrench-and-screwdriver-9453",
        "type": "general/av_wrench-and-screwdriver-9453",
        "category": "Общие"
      },
      {
        "name": "av_x-10327",
        "type": "general/av_x-10327",
        "category": "Общие"
      },
      {
        "name": "av_x",
        "type": "general/av_x",
        "category": "Общие"
      },
      {
        "name": "av_youtube-logo-7121",
        "type": "general/av_youtube-logo-7121",
        "category": "Общие"
      },
      {
        "name": "av_youtube",
        "type": "general/av_youtube",
        "category": "Общие"
      },
      {
        "name": "av_zoom-in",
        "type": "general/av_zoom-in",
        "category": "Общие"
      },
      {
        "name": "av_zoom-out",
        "type": "general/av_zoom-out",
        "category": "Общие"
      }
    ]
  },
  {
    "category": "Медиа",
    "icons": [
      {
        "name": "av_equalizer",
        "type": "media/av_equalizer",
        "category": "Медиа"
      },
      {
        "name": "av_image",
        "type": "media/av_image",
        "category": "Медиа"
      },
      {
        "name": "av_play",
        "type": "media/av_play",
        "category": "Медиа"
      },
      {
        "name": "av_screen",
        "type": "media/av_screen",
        "category": "Медиа"
      },
      {
        "name": "av_tablet",
        "type": "media/av_tablet",
        "category": "Медиа"
      },
      {
        "name": "av_volume",
        "type": "media/av_volume",
        "category": "Медиа"
      }
    ]
  },
  {
    "category": "Плеер",
    "icons": [
      {
        "name": "av_backward",
        "type": "rewind/av_backward",
        "category": "Плеер"
      },
      {
        "name": "av_eject",
        "type": "rewind/av_eject",
        "category": "Плеер"
      },
      {
        "name": "av_fast-backward",
        "type": "rewind/av_fast-backward",
        "category": "Плеер"
      },
      {
        "name": "av_fast-forward",
        "type": "rewind/av_fast-forward",
        "category": "Плеер"
      },
      {
        "name": "av_pause",
        "type": "rewind/av_pause",
        "category": "Плеер"
      },
      {
        "name": "av_record",
        "type": "rewind/av_record",
        "category": "Плеер"
      },
      {
        "name": "av_stop",
        "type": "rewind/av_stop",
        "category": "Плеер"
      }
    ]
  },
  {
    "category": "Настройки",
    "icons": [
      {
        "name": "av_adjust",
        "type": "settings/av_adjust",
        "category": "Настройки"
      },
      {
        "name": "av_battery-empty",
        "type": "settings/av_battery-empty",
        "category": "Настройки"
      },
      {
        "name": "av_battery-full",
        "type": "settings/av_battery-full",
        "category": "Настройки"
      },
      {
        "name": "av_battery-half",
        "type": "settings/av_battery-half",
        "category": "Настройки"
      },
      {
        "name": "av_bell-crossed",
        "type": "settings/av_bell-crossed",
        "category": "Настройки"
      },
      {
        "name": "av_bell",
        "type": "settings/av_bell",
        "category": "Настройки"
      },
      {
        "name": "av_bookmark",
        "type": "settings/av_bookmark",
        "category": "Настройки"
      },
      {
        "name": "av_camera",
        "type": "settings/av_camera",
        "category": "Настройки"
      },
      {
        "name": "av_checkmark",
        "type": "settings/av_checkmark",
        "category": "Настройки"
      },
      {
        "name": "av_cog",
        "type": "settings/av_cog",
        "category": "Настройки"
      },
      {
        "name": "av_cross",
        "type": "settings/av_cross",
        "category": "Настройки"
      },
      {
        "name": "av_exclamation-mark",
        "type": "settings/av_exclamation-mark",
        "category": "Настройки"
      },
      {
        "name": "av_info",
        "type": "settings/av_info",
        "category": "Настройки"
      },
      {
        "name": "av_question-mark",
        "type": "settings/av_question-mark",
        "category": "Настройки"
      },
      {
        "name": "av_speaker-mute",
        "type": "settings/av_speaker-mute",
        "category": "Настройки"
      },
      {
        "name": "av_speaker-volume-down",
        "type": "settings/av_speaker-volume-down",
        "category": "Настройки"
      },
      {
        "name": "av_speaker-volume-up",
        "type": "settings/av_speaker-volume-up",
        "category": "Настройки"
      },
      {
        "name": "av_speaker",
        "type": "settings/av_speaker",
        "category": "Настройки"
      },
      {
        "name": "av_sterisk",
        "type": "settings/av_sterisk",
        "category": "Настройки"
      }
    ]
  },
  {
    "category": "Соцсети",
    "icons": [
      {
        "name": "av_github",
        "type": "social/av_github",
        "category": "Соцсети"
      },
      {
        "name": "av_twitter",
        "type": "social/av_twitter",
        "category": "Соцсети"
      },
      {
        "name": "av_youtube",
        "type": "social/av_youtube",
        "category": "Соцсети"
      }
    ]
  },
  {
    "category": "Система",
    "icons": [
      {
        "name": "av_barcode",
        "type": "system/av_barcode",
        "category": "Система"
      },
      {
        "name": "av_brightness",
        "type": "system/av_brightness",
        "category": "Система"
      },
      {
        "name": "av_bug",
        "type": "system/av_bug",
        "category": "Система"
      },
      {
        "name": "av_cog",
        "type": "system/av_cog",
        "category": "Система"
      },
      {
        "name": "av_info",
        "type": "system/av_info",
        "category": "Система"
      },
      {
        "name": "av_lock",
        "type": "system/av_lock",
        "category": "Система"
      },
      {
        "name": "av_notification",
        "type": "system/av_notification",
        "category": "Система"
      },
      {
        "name": "av_qr_code",
        "type": "system/av_qr_code",
        "category": "Система"
      },
      {
        "name": "av_settings",
        "type": "system/av_settings",
        "category": "Система"
      },
      {
        "name": "av_star",
        "type": "system/av_star",
        "category": "Система"
      },
      {
        "name": "av_sterisk",
        "type": "system/av_sterisk",
        "category": "Система"
      },
      {
        "name": "av_unlock",
        "type": "system/av_unlock",
        "category": "Система"
      },
      {
        "name": "av_warning",
        "type": "system/av_warning",
        "category": "Система"
      }
    ]
  },
  {
    "category": "Время",
    "icons": [
      {
        "name": "av_alarm",
        "type": "time/av_alarm",
        "category": "Время"
      },
      {
        "name": "av_clock",
        "type": "time/av_clock",
        "category": "Время"
      },
      {
        "name": "av_stopwatch",
        "type": "time/av_stopwatch",
        "category": "Время"
      }
    ]
  },
  {
    "category": "Пользователь",
    "icons": [
      {
        "name": "av_profile",
        "type": "user/av_profile",
        "category": "Пользователь"
      },
      {
        "name": "av_users",
        "type": "user/av_users",
        "category": "Пользователь"
      }
    ]
  }
];
