// src/app/pages/ui-demo/icon-ui/icon-registry.ts
// AUTO-GENERATED by regenerate-icon-registry.ps1
// DO NOT EDIT MANUALLY

import { IconMetadata } from './icon-metadata.model';

export interface IconCategory {
  category: string;
  icons: IconMetadata[];
}

export const ICON_REGISTRY: IconCategory[] = [
  {
    "category": "Действия",
    "icons": [
      {
        "name": "av_add",
        "type": "actions/av_add",
        "category": "Действия"
      },
      {
        "name": "av_calculator",
        "type": "actions/av_calculator",
        "category": "Действия"
      },
      {
        "name": "av_check_mark",
        "type": "actions/av_check_mark",
        "category": "Действия"
      },
      {
        "name": "av_close",
        "type": "actions/av_close",
        "category": "Действия"
      },
      {
        "name": "av_copy",
        "type": "actions/av_copy",
        "category": "Действия"
      },
      {
        "name": "av_eraser",
        "type": "actions/av_eraser",
        "category": "Действия"
      },
      {
        "name": "av_exit",
        "type": "actions/av_exit",
        "category": "Действия"
      },
      {
        "name": "av_eye",
        "type": "actions/av_eye",
        "category": "Действия"
      },
      {
        "name": "av_hammer",
        "type": "actions/av_hammer",
        "category": "Действия"
      },
      {
        "name": "av_minus",
        "type": "actions/av_minus",
        "category": "Действия"
      },
      {
        "name": "av_plus",
        "type": "actions/av_plus",
        "category": "Действия"
      },
      {
        "name": "av_save",
        "type": "actions/av_save",
        "category": "Действия"
      },
      {
        "name": "av_search",
        "type": "actions/av_search",
        "category": "Действия"
      },
      {
        "name": "av_trash",
        "type": "actions/av_trash",
        "category": "Действия"
      },
      {
        "name": "av_upload",
        "type": "actions/av_upload",
        "category": "Действия"
      }
    ]
  },

  {
    "category": "Стрелки",
    "icons": [
      {
        "name": "av_arrow_down",
        "type": "arrows/av_arrow_down",
        "category": "Стрелки"
      },
      {
        "name": "av_arrow_down_right",
        "type": "arrows/av_arrow_down_right",
        "category": "Стрелки"
      },
      {
        "name": "av_arrow_left",
        "type": "arrows/av_arrow_left",
        "category": "Стрелки"
      },
      {
        "name": "av_arrow_right",
        "type": "arrows/av_arrow_right",
        "category": "Стрелки"
      },
      {
        "name": "av_arrow_up",
        "type": "arrows/av_arrow_up",
        "category": "Стрелки"
      },
      {
        "name": "av_arrow-down",
        "type": "arrows/av_arrow-down",
        "category": "Стрелки"
      },
      {
        "name": "av_arrow-left",
        "type": "arrows/av_arrow-left",
        "category": "Стрелки"
      },
      {
        "name": "av_arrow-right",
        "type": "arrows/av_arrow-right",
        "category": "Стрелки"
      },
      {
        "name": "av_arrow-up",
        "type": "arrows/av_arrow-up",
        "category": "Стрелки"
      },
      {
        "name": "av_arrows_out",
        "type": "arrows/av_arrows_out",
        "category": "Стрелки"
      },
      {
        "name": "av_chevron-down",
        "type": "arrows/av_chevron-down",
        "category": "Стрелки"
      },
      {
        "name": "av_chevron-left",
        "type": "arrows/av_chevron-left",
        "category": "Стрелки"
      },
      {
        "name": "av_chevron-right",
        "type": "arrows/av_chevron-right",
        "category": "Стрелки"
      },
      {
        "name": "av_chevron-up",
        "type": "arrows/av_chevron-up",
        "category": "Стрелки"
      },
      {
        "name": "av_expand",
        "type": "arrows/av_expand",
        "category": "Стрелки"
      },
      {
        "name": "av_fast_forward",
        "type": "arrows/av_fast_forward",
        "category": "Стрелки"
      },
      {
        "name": "av_triangle-down",
        "type": "arrows/av_triangle-down",
        "category": "Стрелки"
      },
      {
        "name": "av_triangle-left",
        "type": "arrows/av_triangle-left",
        "category": "Стрелки"
      },
      {
        "name": "av_triangle-right",
        "type": "arrows/av_triangle-right",
        "category": "Стрелки"
      },
      {
        "name": "av_triangle-up",
        "type": "arrows/av_triangle-up",
        "category": "Стрелки"
      },
      {
        "name": "av_undo",
        "type": "arrows/av_undo",
        "category": "Стрелки"
      }
    ]
  },

  {
    "category": "Графики",
    "icons": [
      {
        "name": "av_bar_chart",
        "type": "charts/av_bar_chart",
        "category": "Графики"
      },
      {
        "name": "av_line_chart",
        "type": "charts/av_line_chart",
        "category": "Графики"
      },
      {
        "name": "av_pie_chart",
        "type": "charts/av_pie_chart",
        "category": "Графики"
      }
    ]
  },

  {
    "category": "Коммуникация",
    "icons": [
      {
        "name": "av_chat",
        "type": "communication/av_chat",
        "category": "Коммуникация"
      },
      {
        "name": "av_mail",
        "type": "communication/av_mail",
        "category": "Коммуникация"
      },
      {
        "name": "av_phone",
        "type": "communication/av_phone",
        "category": "Коммуникация"
      },
      {
        "name": "av_rss",
        "type": "communication/av_rss",
        "category": "Коммуникация"
      }
    ]
  },

  {
    "category": "Редактор",
    "icons": [
      {
        "name": "av_align_center",
        "type": "editor/av_align_center",
        "category": "Редактор"
      },
      {
        "name": "av_align_right",
        "type": "editor/av_align_right",
        "category": "Редактор"
      },
      {
        "name": "av_align-center",
        "type": "editor/av_align-center",
        "category": "Редактор"
      },
      {
        "name": "av_align-justify",
        "type": "editor/av_align-justify",
        "category": "Редактор"
      },
      {
        "name": "av_align-left",
        "type": "editor/av_align-left",
        "category": "Редактор"
      },
      {
        "name": "av_align-right",
        "type": "editor/av_align-right",
        "category": "Редактор"
      },
      {
        "name": "av_bold",
        "type": "editor/av_bold",
        "category": "Редактор"
      },
      {
        "name": "av_bulleted-list",
        "type": "editor/av_bulleted-list",
        "category": "Редактор"
      },
      {
        "name": "av_edit",
        "type": "editor/av_edit",
        "category": "Редактор"
      },
      {
        "name": "av_font",
        "type": "editor/av_font",
        "category": "Редактор"
      },
      {
        "name": "av_italic",
        "type": "editor/av_italic",
        "category": "Редактор"
      },
      {
        "name": "av_list",
        "type": "editor/av_list",
        "category": "Редактор"
      },
      {
        "name": "av_paint",
        "type": "editor/av_paint",
        "category": "Редактор"
      }
    ]
  },

  {
    "category": "Файлы",
    "icons": [
      {
        "name": "av_excel",
        "type": "files/av_excel",
        "category": "Файлы"
      },
      {
        "name": "av_folder",
        "type": "files/av_folder",
        "category": "Файлы"
      },
      {
        "name": "av_paperclip",
        "type": "files/av_paperclip",
        "category": "Файлы"
      },
      {
        "name": "av_zip",
        "type": "files/av_zip",
        "category": "Файлы"
      }
    ]
  },

  {
    "category": "Общие",
    "icons": [
      {
        "name": "av_book",
        "type": "general/av_book",
        "category": "Общие"
      },
      {
        "name": "av_dice",
        "type": "general/av_dice",
        "category": "Общие"
      },
      {
        "name": "av_earth",
        "type": "general/av_earth",
        "category": "Общие"
      },
      {
        "name": "av_home",
        "type": "general/av_home",
        "category": "Общие"
      },
      {
        "name": "av_house",
        "type": "general/av_house",
        "category": "Общие"
      },
      {
        "name": "av_like",
        "type": "general/av_like",
        "category": "Общие"
      },
      {
        "name": "av_road",
        "type": "general/av_road",
        "category": "Общие"
      },
      {
        "name": "av_tag",
        "type": "general/av_tag",
        "category": "Общие"
      },
      {
        "name": "av_ticket",
        "type": "general/av_ticket",
        "category": "Общие"
      },
      {
        "name": "av_trophy",
        "type": "general/av_trophy",
        "category": "Общие"
      }
    ]
  },

  {
    "category": "Медиа",
    "icons": [
      {
        "name": "av_equalizer",
        "type": "media/av_equalizer",
        "category": "Медиа"
      },
      {
        "name": "av_image",
        "type": "media/av_image",
        "category": "Медиа"
      },
      {
        "name": "av_play",
        "type": "media/av_play",
        "category": "Медиа"
      },
      {
        "name": "av_screen",
        "type": "media/av_screen",
        "category": "Медиа"
      },
      {
        "name": "av_tablet",
        "type": "media/av_tablet",
        "category": "Медиа"
      },
      {
        "name": "av_volume",
        "type": "media/av_volume",
        "category": "Медиа"
      }
    ]
  },

  {
    "category": "Плеер",
    "icons": [
      {
        "name": "av_backward",
        "type": "rewind/av_backward",
        "category": "Плеер"
      },
      {
        "name": "av_eject",
        "type": "rewind/av_eject",
        "category": "Плеер"
      },
      {
        "name": "av_fast-backward",
        "type": "rewind/av_fast-backward",
        "category": "Плеер"
      },
      {
        "name": "av_fast-forward",
        "type": "rewind/av_fast-forward",
        "category": "Плеер"
      },
      {
        "name": "av_pause",
        "type": "rewind/av_pause",
        "category": "Плеер"
      },
      {
        "name": "av_record",
        "type": "rewind/av_record",
        "category": "Плеер"
      },
      {
        "name": "av_stop",
        "type": "rewind/av_stop",
        "category": "Плеер"
      }
    ]
  },

  {
    "category": "Настройки",
    "icons": [
      {
        "name": "av_adjust",
        "type": "settings/av_adjust",
        "category": "Настройки"
      },
      {
        "name": "av_battery-empty",
        "type": "settings/av_battery-empty",
        "category": "Настройки"
      },
      {
        "name": "av_battery-full",
        "type": "settings/av_battery-full",
        "category": "Настройки"
      },
      {
        "name": "av_battery-half",
        "type": "settings/av_battery-half",
        "category": "Настройки"
      },
      {
        "name": "av_bell",
        "type": "settings/av_bell",
        "category": "Настройки"
      },
      {
        "name": "av_bell-crossed",
        "type": "settings/av_bell-crossed",
        "category": "Настройки"
      },
      {
        "name": "av_bookmark",
        "type": "settings/av_bookmark",
        "category": "Настройки"
      },
      {
        "name": "av_camera",
        "type": "settings/av_camera",
        "category": "Настройки"
      },
      {
        "name": "av_checkmark",
        "type": "settings/av_checkmark",
        "category": "Настройки"
      },
      {
        "name": "av_cog",
        "type": "settings/av_cog",
        "category": "Настройки"
      },
      {
        "name": "av_cross",
        "type": "settings/av_cross",
        "category": "Настройки"
      },
      {
        "name": "av_exclamation-mark",
        "type": "settings/av_exclamation-mark",
        "category": "Настройки"
      },
      {
        "name": "av_info",
        "type": "settings/av_info",
        "category": "Настройки"
      },
      {
        "name": "av_question-mark",
        "type": "settings/av_question-mark",
        "category": "Настройки"
      },
      {
        "name": "av_speaker",
        "type": "settings/av_speaker",
        "category": "Настройки"
      },
      {
        "name": "av_speaker-mute",
        "type": "settings/av_speaker-mute",
        "category": "Настройки"
      },
      {
        "name": "av_speaker-volume-down",
        "type": "settings/av_speaker-volume-down",
        "category": "Настройки"
      },
      {
        "name": "av_speaker-volume-up",
        "type": "settings/av_speaker-volume-up",
        "category": "Настройки"
      },
      {
        "name": "av_sterisk",
        "type": "settings/av_sterisk",
        "category": "Настройки"
      }
    ]
  },

  {
    "category": "Соцсети",
    "icons": [
      {
        "name": "av_github",
        "type": "social/av_github",
        "category": "Соцсети"
      },
      {
        "name": "av_twitter",
        "type": "social/av_twitter",
        "category": "Соцсети"
      },
      {
        "name": "av_youtube",
        "type": "social/av_youtube",
        "category": "Соцсети"
      }
    ]
  },

  {
    "category": "Система",
    "icons": [
      {
        "name": "av_barcode",
        "type": "system/av_barcode",
        "category": "Система"
      },
      {
        "name": "av_brightness",
        "type": "system/av_brightness",
        "category": "Система"
      },
      {
        "name": "av_bug",
        "type": "system/av_bug",
        "category": "Система"
      },
      {
        "name": "av_cog",
        "type": "system/av_cog",
        "category": "Система"
      },
      {
        "name": "av_info",
        "type": "system/av_info",
        "category": "Система"
      },
      {
        "name": "av_lock",
        "type": "system/av_lock",
        "category": "Система"
      },
      {
        "name": "av_notification",
        "type": "system/av_notification",
        "category": "Система"
      },
      {
        "name": "av_qr_code",
        "type": "system/av_qr_code",
        "category": "Система"
      },
      {
        "name": "av_settings",
        "type": "system/av_settings",
        "category": "Система"
      },
      {
        "name": "av_star",
        "type": "system/av_star",
        "category": "Система"
      },
      {
        "name": "av_sterisk",
        "type": "system/av_sterisk",
        "category": "Система"
      },
      {
        "name": "av_unlock",
        "type": "system/av_unlock",
        "category": "Система"
      },
      {
        "name": "av_warning",
        "type": "system/av_warning",
        "category": "Система"
      }
    ]
  },

  {
    "category": "Время",
    "icons": [
      {
        "name": "av_alarm",
        "type": "time/av_alarm",
        "category": "Время"
      },
      {
        "name": "av_clock",
        "type": "time/av_clock",
        "category": "Время"
      },
      {
        "name": "av_stopwatch",
        "type": "time/av_stopwatch",
        "category": "Время"
      }
    ]
  },

  {
    "category": "Пользователь",
    "icons": [
      {
        "name": "av_profile",
        "type": "user/av_profile",
        "category": "Пользователь"
      },
      {
        "name": "av_users",
        "type": "user/av_users",
        "category": "Пользователь"
      }
    ]
  }
];

